import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => (
  <div className="Home-wrapper">
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="home-wrapper">
      <h1> Welcome to Next JS project of Thanh Minh </h1>{' '}
    </div>
  </div>
);

export default Home;
